version: 1.0.{build}
clone_depth: 1
build:
  parallel: true
  verbosity: detailed
notifications:
- provider: Email
  to:
  - rafanery0@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true